import type { Fragment, Volume } from "./types";

/**
 * Sample library — 8 volumes across 3 shelves, one unread, one unannotated.
 * Replace this content with the real saves before deploy (FLOWS.md: the seed
 * file ships the data, or a reviewer opens an empty library).
 */

export const seedVolumes: Volume[] = [
  {
    id: "v-slow-web",
    title: "The Case for a Slower Web",
    author: "N. Adeyemi",
    link: "https://example.substack.com/p/slower-web",
    source: "Substack",
    dateSaved: "2026-08-11T09:00:00.000Z",
    shelf: "Attention",
    articleSummary:
      "Argues that latency budgets became a proxy for quality, and that speed optimisations often remove the pauses where understanding happens. Proposes designing for comprehension time rather than load time.",
    keyPoints: [
      "Speed metrics became a proxy for quality.",
      "Removing every pause removes the time to understand.",
      "Comprehension time is the number that matters.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "v-defaults",
    title: "Defaults Are Policy",
    author: "K. Oyelaran",
    link: "https://example.org/defaults-are-policy",
    source: "Substack",
    dateSaved: "2026-08-06T14:20:00.000Z",
    shelf: "Attention",
    articleSummary:
      "Treats default settings as governance rather than convenience, showing that the option nobody changes determines almost all real behaviour.",
    keyPoints: [
      "A default is a decision made for everyone.",
      "Almost nobody changes a default.",
      "Defaults deserve the scrutiny features get.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "v-figma-craft",
    title: "What Craft Looks Like in a Tool",
    author: "L. Barreto",
    link: "https://medium.com/@lbarreto/craft-in-a-tool",
    source: "Medium",
    dateSaved: "2026-08-01T11:45:00.000Z",
    shelf: "Craft",
    articleSummary:
      "Looks at how software tools encode a point of view about the work they support, and argues that a tool's defaults teach a practice.",
    keyPoints: [
      "Tools encode a view of the work.",
      "Defaults teach a practice.",
      "Neutral tooling is a myth.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "v-writing-ui",
    title: "Writing Is the Interface",
    author: "C. Marsh",
    link: "https://www.linkedin.com/pulse/writing-is-the-interface",
    source: "LinkedIn",
    dateSaved: "2026-07-27T16:05:00.000Z",
    shelf: "Craft",
    articleSummary:
      "Makes the case that most interface problems are writing problems wearing a visual costume, and that clarity of language precedes clarity of layout.",
    keyPoints: [
      "Most interface problems are writing problems.",
      "Layout cannot rescue unclear language.",
      "Naming is the first design decision.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "v-scale-cost",
    title: "The Cost of Scale",
    author: "V. Ramachandran",
    link: "https://example.org/cost-of-scale",
    source: "Substack",
    dateSaved: "2026-07-19T10:30:00.000Z",
    shelf: "Research",
    articleSummary:
      "Examines what gets flattened when a product grows, arguing that the operations of scale quietly select for the users easiest to serve.",
    keyPoints: [
      "Scale selects for the easiest users.",
      "What is hard to measure gets dropped first.",
      "Growth changes who the product is for.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "v-archives",
    title: "On Personal Archives",
    author: "F. Nakamura",
    link: "https://example.org/personal-archives",
    source: "Substack",
    dateSaved: "2026-07-12T08:15:00.000Z",
    shelf: "Research",
    articleSummary:
      "A history of private collections, arguing that an archive is defined by what its keeper chose to say about each item rather than by what it contains.",
    keyPoints: [
      "An archive is shaped by its keeper's annotations.",
      "Contents alone do not make a collection.",
      "The commentary is the artefact.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "v-ai-literacy",
    title: "Reading Machines",
    author: "G. Petrova",
    link: "https://medium.com/@gpetrova/reading-machines",
    source: "Medium",
    dateSaved: "2026-07-04T13:40:00.000Z",
    shelf: "AI and design",
    articleSummary:
      "Considers what it means to read something a machine wrote, and whether the usual reading strategies survive when there is no intention behind the text.",
    keyPoints: [
      "Reading assumes an intending author.",
      "Machine text has no intention to recover.",
      "New reading strategies are needed, not old ones applied harder.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: true,
    coverFamily: "clay",
  },
  {
    id: "v-interfaces-agents",
    title: "Interfaces for Agents",
    author: "B. Toure",
    link: "https://example.substack.com/p/interfaces-for-agents",
    source: "Substack",
    dateSaved: "2026-06-25T15:10:00.000Z",
    shelf: "AI and design",
    articleSummary:
      "Surveys the emerging patterns for supervising software that acts on your behalf, and argues the hard problem is legibility of intent rather than control.",
    keyPoints: [
      "Supervision, not control, is the design problem.",
      "The user needs to see what the agent intends.",
      "Undo matters more than approval.",
    ],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "v-feelings",
    // Seeded from the URL only — Medium returns 403 to server-side fetches, so
    // the body was never read. Empty summary and keyPoints are the real state
    // of a save whose enrichment has not run: shelf "Unsorted", fallback cover.
    title: "AI Got Good at Feelings. Now What?",
    author: "bydivya",
    link: "https://medium.com/@bydivya/ai-got-good-at-feelings-now-what-4741d1be1e94",
    source: "Medium",
    dateSaved: "2026-08-27T10:35:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "v-burry-circular",
    title: "The Circular Financing Map",
    author: "Michael Burry",
    link: "https://substack.com/@michaeljburry/note/c-313290594",
    source: "Substack",
    dateSaved: "2026-08-27T10:20:00.000Z",
    shelf: "Attention",
    articleSummary:
      "A short note on Cassandra Unchained pointing at a circular financing map published by Bloomberg. Burry says he has spent a week and a half working through post-earnings filings, plans to go through Coreweave's and Nebius's 10-Qs next, and states that what he has found so far is worse than the diagram shows.",
    keyPoints: [
      "A Bloomberg circular financing diagram is the starting point for the claim.",
      "The reading is grounded in a week and a half of post-earnings filings, not commentary.",
      "He states plainly that what he has seen is worse than the map depicts.",
    ],
    recommendations: [],
    tags: ["AI", "Finance", "Evidence"],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "v-attention",
    title: "The Attention Economy Ate Design",
    author: "M. Halloran",
    link: "https://example.substack.com/p/attention-economy",
    source: "Substack",
    dateSaved: "2026-08-14T09:12:00.000Z",
    shelf: "Attention",
    articleSummary:
      "Argues that engagement metrics quietly became the design brief. Most interface patterns of the last decade optimise for time spent rather than task completed, and the piece proposes measuring the shortest path to done instead.",
    keyPoints: [
      "Engagement metrics were adopted because they were easy to measure, not because they were right.",
      "Most interface patterns of the last decade optimise for time spent.",
      "A shorter session is usually the successful one.",
    ],
    tags: ["Metrics", "Critique"],
    recommendations: [
      {
        title: "Goodhart's Law, Revisited",
        link: "https://www.worksinprogress.co/",
        source: "Works in Progress",
        why: "Follows your point that the metric writes the brief into how institutions pick targets.",
      },
      {
        title: "The Tyranny of Metrics",
        link: "https://press.princeton.edu/",
        source: "Princeton University Press",
        why: "Book-length version of the argument you were reaching for in reviews.",
      },
      {
        title: "Against Dwell Time",
        link: "https://www.nngroup.com/",
        source: "Nielsen Norman Group",
        why: "Practitioner counterpoint on when time-on-task is and is not a success signal.",
      },
    ],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "v-material",
    title: "Treating Models as a Design Material",
    author: "R. Feldman",
    link: "https://example.substack.com/p/models-as-material",
    source: "Substack",
    dateSaved: "2026-07-21T11:05:00.000Z",
    shelf: "AI and design",
    articleSummary:
      "Frames language models as an unreliable material with a grain, closer to wood than to a database. Design work becomes finding the shapes that survive the material's variance.",
    keyPoints: [
      "Models behave like a material with a grain, not like a database.",
      "Variance should be designed with, not engineered away.",
      "The interesting question is what the interface does when the model is wrong.",
    ],
    tags: ["AI", "Craft"],
    recommendations: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "v-generated",
    title: "How Do You Review a Generated Interface?",
    author: "H. Vance",
    link: "https://example.substack.com/p/reviewing-generated-ui",
    source: "Substack",
    dateSaved: "2026-06-28T13:00:00.000Z",
    shelf: "AI and design",
    articleSummary:
      "Notes that design critique assumes an author who can explain intent. Asks what critique becomes when the artefact has no author left to question, and argues it must shift to consequence.",
    keyPoints: [
      "Design critique depends on an author who can explain intent.",
      "Generated artefacts have no intent to interrogate.",
      "Critique must shift from intent to consequence.",
    ],
    tags: ["AI", "Critique"],
    recommendations: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "v-taste",
    title: "Taste Is a Skill, Not a Gift",
    author: "J. Okonkwo",
    link: "https://medium.com/@jokonkwo/taste-is-a-skill",
    source: "Medium",
    dateSaved: "2026-08-02T17:40:00.000Z",
    shelf: "Craft",
    articleSummary:
      "Breaks taste into three learnable components: exposure, articulation, and revision. Claims the bottleneck for most designers is the second, because they can tell good from bad but cannot say why.",
    keyPoints: [
      "Taste has three components: exposure, articulation, revision.",
      "Articulation is the component most designers skip.",
      "Taste is trainable, not innate.",
    ],
    tags: ["Craft", "Career"],
    recommendations: [
      {
        title: "Taste, Explained",
        link: "https://aworkinglibrary.com/",
        source: "A Working Library",
        why: "Takes your line about articulation being the bottleneck and puts it in writing practice.",
      },
      {
        title: "On Critique",
        link: "https://www.are.na/",
        source: "Are.na",
        why: "Collections of people practising exactly the articulation you say is missing.",
      },
      {
        title: "The Craft Is the Argument",
        link: "https://www.robinsloan.com/",
        source: "Robin Sloan",
        why: "Craft writing that models saying why, not just knowing why.",
      },
    ],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "v-fidelity",
    title: "Against High-Fidelity Prototypes",
    author: "P. Osei",
    link: "https://medium.com/@posei/against-high-fidelity",
    source: "Medium",
    dateSaved: "2026-07-09T15:22:00.000Z",
    shelf: "Process",
    articleSummary:
      "Argues that polish arrives too early and freezes decisions that should stay liquid. Recommends staying deliberately rough until the structure has settled.",
    keyPoints: [
      "Polish arrives before structure is settled.",
      "Fidelity acts as a commitment device.",
      "Staying rough keeps decisions negotiable.",
    ],
    tags: ["Process"],
    recommendations: [],
    unread: false,
    unannotated: true,
    coverFamily: "slate",
  },
  {
    id: "v-revision",
    title: "Revision Is the Whole Job",
    author: "T. Merrow",
    link: "https://www.linkedin.com/pulse/revision-is-the-whole-job",
    source: "LinkedIn",
    dateSaved: "2026-06-11T12:10:00.000Z",
    shelf: "Craft",
    articleSummary:
      "A short piece on second drafts, arguing that the first version of anything is only a way of discovering what the work is actually about.",
    keyPoints: [
      "The first draft discovers what the work is about.",
      "Revision is where the actual thinking happens.",
      "Treating drafts as failed finals wastes them.",
    ],
    tags: ["Process", "Craft"],
    recommendations: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "v-debt",
    title: "Research Debt",
    author: "D. Achterberg",
    link: "https://example.org/research-debt",
    source: "Substack",
    dateSaved: "2026-06-19T10:15:00.000Z",
    shelf: "Research",
    articleSummary:
      "Describes the accumulated cost of ideas that were never explained well, and makes the case that distillation is real work rather than a summary of it.",
    keyPoints: [
      "Poorly explained ideas accumulate a real cost.",
      "Distillation is work, not a summary of work.",
      "Difficulty of entry is a design failure, not a filter.",
    ],
    tags: ["Research", "Writing"],
    recommendations: [
      {
        title: "Research Debt (Distill)",
        link: "https://distill.pub/2017/research-debt/",
        source: "Distill",
        why: "The original source of the idea you connected to your own retention problem.",
      },
      {
        title: "Explorable Explanations",
        link: "https://explorabl.es/",
        source: "Explorable Explanations",
        why: "Distillation treated as real work, which is the part you said nobody funds.",
      },
      {
        title: "Writing as Thinking",
        link: "https://www.newyorker.com/",
        source: "The New Yorker",
        why: "The second-pass argument applied to prose rather than research.",
      },
    ],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "v-legibility",
    title: "The Legibility of Systems",
    author: "S. Mbeki",
    link: "https://example.org/legibility-of-systems",
    source: "Substack",
    dateSaved: "2026-06-04T19:45:00.000Z",
    shelf: "Research",
    articleSummary:
      "Applies Scott's idea of legibility to software: systems get simplified so they can be measured, and the simplification quietly becomes the thing people design for.",
    keyPoints: [
      "Systems get simplified so they can be measured.",
      "The simplification becomes what people design for.",
      "Legibility serves the observer, not the observed.",
    ],
    tags: ["Research", "Systems"],
    recommendations: [],
    unread: true,
    unannotated: false,
    coverFamily: "sage",
  },

/* ---------------------------------------------------------------------------
 * DEMO FILLER — delete this block and its fragments when the real saves land.
 * Enough books to make the shelf read as a library rather than a sample.
 * ------------------------------------------------------------------------- */
  {
    id: "d-00",
    title: "The Half-Life of a Bookmark",
    author: "",
    link: "https://example.org/d-00",
    source: "Substack",
    dateSaved: "2026-08-07T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-01",
    title: "Notifications Are a Design Choice",
    author: "",
    link: "https://example.org/d-01",
    source: "Medium",
    dateSaved: "2026-08-05T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-02",
    title: "On Not Finishing Things",
    author: "",
    link: "https://example.org/d-02",
    source: "Substack",
    dateSaved: "2026-08-03T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-03",
    title: "The Feed Is Not a Library",
    author: "",
    link: "https://example.org/d-03",
    source: "LinkedIn",
    dateSaved: "2026-08-01T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-04",
    title: "Deep Work Is a Scheduling Problem",
    author: "",
    link: "https://example.org/d-04",
    source: "Medium",
    dateSaved: "2026-07-30T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-05",
    title: "Reading Speed Is a Vanity Metric",
    author: "",
    link: "https://example.org/d-05",
    source: "Substack",
    dateSaved: "2026-07-28T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-06",
    title: "What Gets Measured Gets Gamed",
    author: "",
    link: "https://example.org/d-06",
    source: "Substack",
    dateSaved: "2026-07-26T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-07",
    title: "Slow Media",
    author: "",
    link: "https://example.org/d-07",
    source: "Substack",
    dateSaved: "2026-07-24T10:00:00.000Z",
    shelf: "Attention",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-08",
    title: "Against the Style Guide",
    author: "",
    link: "https://example.org/d-08",
    source: "Medium",
    dateSaved: "2026-07-22T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-09",
    title: "The Second Draft Problem",
    author: "",
    link: "https://example.org/d-09",
    source: "Substack",
    dateSaved: "2026-07-20T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-10",
    title: "Constraint as Method",
    author: "",
    link: "https://example.org/d-10",
    source: "Medium",
    dateSaved: "2026-07-18T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-11",
    title: "Typography Is Argument",
    author: "",
    link: "https://example.org/d-11",
    source: "Substack",
    dateSaved: "2026-07-16T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-12",
    title: "Learning by Copying",
    author: "",
    link: "https://example.org/d-12",
    source: "LinkedIn",
    dateSaved: "2026-07-14T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-13",
    title: "The Portfolio Is the Wrong Artefact",
    author: "",
    link: "https://example.org/d-13",
    source: "Medium",
    dateSaved: "2026-07-12T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-14",
    title: "Notes on Sketching",
    author: "",
    link: "https://example.org/d-14",
    source: "Substack",
    dateSaved: "2026-07-10T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-15",
    title: "Why Critique Fails",
    author: "",
    link: "https://example.org/d-15",
    source: "Substack",
    dateSaved: "2026-07-08T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-16",
    title: "Craft Under Deadline",
    author: "",
    link: "https://example.org/d-16",
    source: "Medium",
    dateSaved: "2026-07-06T10:00:00.000Z",
    shelf: "Craft",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-17",
    title: "The Replication Gap",
    author: "",
    link: "https://example.org/d-17",
    source: "Substack",
    dateSaved: "2026-07-04T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-18",
    title: "Methods Are the Result",
    author: "",
    link: "https://example.org/d-18",
    source: "Substack",
    dateSaved: "2026-07-02T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-19",
    title: "On Reading Papers Badly",
    author: "",
    link: "https://example.org/d-19",
    source: "Medium",
    dateSaved: "2026-06-30T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-20",
    title: "Citation Is Not Evidence",
    author: "",
    link: "https://example.org/d-20",
    source: "Substack",
    dateSaved: "2026-06-28T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-21",
    title: "Sample Size and Story Size",
    author: "",
    link: "https://example.org/d-21",
    source: "Substack",
    dateSaved: "2026-06-26T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-22",
    title: "Field Notes as a Form",
    author: "",
    link: "https://example.org/d-22",
    source: "Medium",
    dateSaved: "2026-06-24T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-23",
    title: "The Literature Nobody Reads",
    author: "",
    link: "https://example.org/d-23",
    source: "Substack",
    dateSaved: "2026-06-22T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-24",
    title: "Qualitative Is Not Soft",
    author: "",
    link: "https://example.org/d-24",
    source: "LinkedIn",
    dateSaved: "2026-06-20T10:00:00.000Z",
    shelf: "Research",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-25",
    title: "Prompting Is Interface Design",
    author: "",
    link: "https://example.org/d-25",
    source: "Substack",
    dateSaved: "2026-06-18T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-26",
    title: "Evaluating Generated Work",
    author: "",
    link: "https://example.org/d-26",
    source: "Medium",
    dateSaved: "2026-06-16T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-27",
    title: "The Copilot Metaphor Is Wrong",
    author: "",
    link: "https://example.org/d-27",
    source: "Substack",
    dateSaved: "2026-06-14T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-28",
    title: "Latency Changes the Interaction",
    author: "",
    link: "https://example.org/d-28",
    source: "Substack",
    dateSaved: "2026-06-12T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-29",
    title: "Design Systems for Uncertain Output",
    author: "",
    link: "https://example.org/d-29",
    source: "Medium",
    dateSaved: "2026-06-10T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-30",
    title: "Who Reviews the Model's Work",
    author: "",
    link: "https://example.org/d-30",
    source: "LinkedIn",
    dateSaved: "2026-06-08T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-31",
    title: "Explaining Without Anthropomorphising",
    author: "",
    link: "https://example.org/d-31",
    source: "Substack",
    dateSaved: "2026-06-06T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-32",
    title: "Interfaces That Admit Doubt",
    author: "",
    link: "https://example.org/d-32",
    source: "Substack",
    dateSaved: "2026-06-04T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-33",
    title: "The Undo Problem",
    author: "",
    link: "https://example.org/d-33",
    source: "Medium",
    dateSaved: "2026-06-02T10:00:00.000Z",
    shelf: "AI and design",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-34",
    title: "Working in Public",
    author: "",
    link: "https://example.org/d-34",
    source: "Substack",
    dateSaved: "2026-05-31T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-35",
    title: "Standups Are a Symptom",
    author: "",
    link: "https://example.org/d-35",
    source: "LinkedIn",
    dateSaved: "2026-05-29T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "dusk",
  },
  {
    id: "d-36",
    title: "Estimating Is Guessing With Ceremony",
    author: "",
    link: "https://example.org/d-36",
    source: "Medium",
    dateSaved: "2026-05-27T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "ember",
  },
  {
    id: "d-37",
    title: "The Cost of Context Switching",
    author: "",
    link: "https://example.org/d-37",
    source: "Substack",
    dateSaved: "2026-05-25T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-38",
    title: "Documentation as a Product",
    author: "",
    link: "https://example.org/d-38",
    source: "Substack",
    dateSaved: "2026-05-23T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
  {
    id: "d-39",
    title: "Small Teams, Long Horizons",
    author: "",
    link: "https://example.org/d-39",
    source: "Medium",
    dateSaved: "2026-05-21T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "slate",
  },
  {
    id: "d-40",
    title: "Rituals That Outlive Their Reason",
    author: "",
    link: "https://example.org/d-40",
    source: "LinkedIn",
    dateSaved: "2026-05-19T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "sage",
  },
  {
    id: "d-41",
    title: "Deciding Without Consensus",
    author: "",
    link: "https://example.org/d-41",
    source: "Substack",
    dateSaved: "2026-05-17T10:00:00.000Z",
    shelf: "Process",
    articleSummary: "",
    keyPoints: [],
    recommendations: [],
    tags: [],
    unread: false,
    unannotated: false,
    coverFamily: "clay",
  },
];

export const seedFragments: Fragment[] = [
  {
    id: "f-v-slow-web",
    volumeId: "v-slow-web",
    passage:
      "Speed metrics became a proxy for quality.",
    thought:
      "Not every wait is friction. Some of them are where the thinking goes.",
    rawThought:
      "",
    date: "2026-08-11T09:00:00.000Z",
  },
  {
    id: "f-v-defaults",
    volumeId: "v-defaults",
    passage:
      "A default is a decision made for everyone.",
    thought:
      "The invisible-interface piece and this one are the same argument. Nobody reviews the defaults, and the defaults are the product.",
    rawThought:
      "the the invisible interface piece and this one are basically the same argument um nobody reviews the defaults and the defaults are the product",
    date: "2026-08-06T14:20:00.000Z",
  },
  {
    id: "f-v-figma-craft",
    volumeId: "v-figma-craft",
    passage:
      "Tools encode a view of the work.",
    thought:
      "Useful for the portfolio: the tool taught the habit, not the other way round.",
    rawThought:
      "",
    date: "2026-08-01T11:45:00.000Z",
  },
  {
    id: "f-v-writing-ui",
    volumeId: "v-writing-ui",
    passage:
      "Most interface problems are writing problems.",
    thought:
      "Every time a screen felt broken this year it was actually the words. Worth saying out loud in critique.",
    rawThought:
      "every time a screen felt broken this year um it was actually it was the words worth saying out loud in critique",
    date: "2026-07-27T16:05:00.000Z",
  },
  {
    id: "f-v-scale-cost",
    volumeId: "v-scale-cost",
    passage:
      "Scale selects for the easiest users.",
    thought:
      "Same shape as legibility \u2014 the thing gets simplified so it can be run, and then the simplification becomes the goal.",
    rawThought:
      "",
    date: "2026-07-19T10:30:00.000Z",
  },
  {
    id: "f-v-archives",
    volumeId: "v-archives",
    passage:
      "An archive is shaped by its keeper's annotations.",
    thought:
      "This is literally the product. The annotation is what makes a pile into a collection.",
    rawThought:
      "okay this is this is literally the product um the annotation is what makes a pile into a collection",
    date: "2026-07-12T08:15:00.000Z",
  },
  {
    id: "f-v-ai-literacy",
    volumeId: "v-ai-literacy",
    passage:
      "Reading assumes an intending author.",
    thought:
      "",
    rawThought:
      "",
    date: "2026-07-04T13:40:00.000Z",
  },
  {
    id: "f-v-interfaces-agents",
    volumeId: "v-interfaces-agents",
    passage:
      "Supervision, not control, is the design problem.",
    thought:
      "Undo over approval. That is the whole insight and I keep forgetting it.",
    rawThought:
      "",
    date: "2026-06-25T15:10:00.000Z",
  },
  {
    id: "f-burry-1",
    volumeId: "v-burry-circular",
    passage:
      "This is the latest circular financing map from today's Bloomberg article. I have spend the last week and a half going through all these filings post-earnings, and I am looking forward to tearing apart more 10Qs from Coreweave and Nebius soon. From what I have seen it is worse than this.",
    thought:
      "Four sentences and a diagram, and the diagram is doing all of the arguing. Worth remembering that the artefact can be the whole claim — the prose is just a caption telling you where to look.",
    rawThought:
      "okay so four sentences and a diagram and the the diagram is doing all of the arguing here um worth remembering that the artefact can be the whole claim like the prose is just a caption telling you where to look",
    date: "2026-08-27T10:20:00.000Z",
  },
  {
    id: "f-1",
    volumeId: "v-attention",
    passage:
      "We never chose to optimise for time spent. We chose a metric that was easy to measure, and it chose the rest for us.",
    thought:
      "This is the argument I keep failing to make in reviews \u2014 the metric isn't a neutral instrument, it writes the brief.",
    rawThought:
      "okay so this is this is the argument I keep like failing to make in reviews um that the metric isn't a it's not a neutral instrument right it writes the brief",
    date: "2026-08-24T09:12:00.000Z",
  },
  {
    id: "f-2",
    volumeId: "v-attention",
    passage:
      "A shorter session is not a failed session. It is, in most products, the entire point.",
    thought:
      "Worth stealing for the portfolio narrative. Measure the shortest path to done, not dwell time.",
    rawThought:
      "",
    date: "2026-08-25T07:55:00.000Z",
  },
  {
    id: "f-3",
    volumeId: "v-material",
    passage:
      "You do not fight the grain of a material. You find the cuts that work with it.",
    thought:
      "Best framing I've read for designing with models. Variance isn't a bug to design around \u2014 it's the grain.",
    rawThought:
      "this is the best framing I've I've read for for designing with models um variance isn't a bug that you design around it's it's the grain",
    date: "2026-08-22T11:05:00.000Z",
  },
  {
    id: "f-4",
    volumeId: "v-material",
    passage:
      "The question is not whether the model is right. It is what the interface does on the occasions it is wrong.",
    thought:
      "Design the wrong case first. That's the whole discipline in one line.",
    rawThought:
      "",
    date: "2026-08-22T11:40:00.000Z",
  },
  {
    id: "f-5",
    volumeId: "v-generated",
    passage:
      "Critique assumes an author who can be asked what they meant. Remove the author and you are left describing weather.",
    thought:
      "This is the interview answer. Critique of generated work has to move from intent to consequence.",
    rawThought:
      "",
    date: "2026-08-19T13:00:00.000Z",
  },
  {
    id: "f-6",
    volumeId: "v-taste",
    passage:
      "Most designers can reliably tell good from bad. Far fewer can say why, and that gap is the whole career.",
    thought:
      "Articulation is the bottleneck, not perception. Exactly why saving without saying why is worthless.",
    rawThought:
      "so articulation is the is the bottleneck not not perception which is exactly why um saving something without saying why is is basically worthless",
    date: "2026-08-23T17:40:00.000Z",
  },
  {
    id: "f-7",
    volumeId: "v-taste",
    passage:
      "Exposure without articulation produces a person with opinions and no arguments.",
    thought:
      "Uncomfortably close to how I've been reading for the last two years.",
    rawThought:
      "",
    date: "2026-08-23T18:02:00.000Z",
  },
  {
    id: "f-8",
    volumeId: "v-fidelity",
    passage:
      "Polish is a commitment device. The moment it looks finished, the structure stops being negotiable.",
    thought:
      "",
    rawThought:
      "",
    date: "2026-08-20T15:22:00.000Z",
  },
  {
    id: "f-9",
    volumeId: "v-revision",
    passage:
      "The first draft is not a worse version of the final one. It is a different kind of object \u2014 a way of finding out what you are making.",
    thought:
      "Reframes the ugly first pass as research rather than failure. Useful for defending early rough work.",
    rawThought:
      "",
    date: "2026-08-16T12:10:00.000Z",
  },
  {
    id: "f-10",
    volumeId: "v-debt",
    passage:
      "Distillation is not a summary of the work. It is work, and it is almost never funded.",
    thought:
      "Same shape as the retention problem I'm building for \u2014 the second pass is where the value is, and nobody makes time for it.",
    rawThought:
      "",
    date: "2026-08-18T10:15:00.000Z",
  },
  {
    id: "f-11",
    volumeId: "v-debt",
    passage:
      "A field can be full of results and still be hard to enter, and that difficulty is a design failure, not a filter.",
    thought:
      "The 'difficulty as filter' excuse shows up in tools too. Worth pushing on.",
    rawThought:
      "",
    date: "2026-08-18T10:50:00.000Z",
  },
  {
    id: "f-d-00",
    volumeId: "d-00",
    passage: "The Half-Life of a Bookmark.",
    thought:
      "Saved is not kept. The bookmark was always a way of not deciding.",
    rawThought: "",
    date: "2026-08-07T10:00:00.000Z",
  },
  {
    id: "f-d-01",
    volumeId: "d-01",
    passage: "Notifications Are a Design Choice.",
    thought:
      "Nobody owns the interrupt budget, so everyone spends it.",
    rawThought: "",
    date: "2026-08-05T10:00:00.000Z",
  },
  {
    id: "f-d-02",
    volumeId: "d-02",
    passage: "On Not Finishing Things.",
    thought:
      "Abandoning well is a skill nobody teaches.",
    rawThought: "",
    date: "2026-08-03T10:00:00.000Z",
  },
  {
    id: "f-d-03",
    volumeId: "d-03",
    passage: "The Feed Is Not a Library.",
    thought:
      "A feed forgets on purpose. That is the whole difference.",
    rawThought: "",
    date: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "f-d-04",
    volumeId: "d-04",
    passage: "Deep Work Is a Scheduling Problem.",
    thought:
      "It was never about focus. It was about who owns my calendar.",
    rawThought: "",
    date: "2026-07-30T10:00:00.000Z",
  },
  {
    id: "f-d-05",
    volumeId: "d-05",
    passage: "Reading Speed Is a Vanity Metric.",
    thought:
      "Pages per week measures nothing I actually want.",
    rawThought: "",
    date: "2026-07-28T10:00:00.000Z",
  },
  {
    id: "f-d-06",
    volumeId: "d-06",
    passage: "What Gets Measured Gets Gamed.",
    thought:
      "The other half of Goodhart nobody quotes.",
    rawThought: "",
    date: "2026-07-26T10:00:00.000Z",
  },
  {
    id: "f-d-07",
    volumeId: "d-07",
    passage: "Slow Media.",
    thought:
      "Worth stealing the framing, not the aesthetics.",
    rawThought: "",
    date: "2026-07-24T10:00:00.000Z",
  },
  {
    id: "f-d-08",
    volumeId: "d-08",
    passage: "Against the Style Guide.",
    thought:
      "Rules are compressed judgement. Useful until they replace it.",
    rawThought: "",
    date: "2026-07-22T10:00:00.000Z",
  },
  {
    id: "f-d-09",
    volumeId: "d-09",
    passage: "The Second Draft Problem.",
    thought:
      "Everyone funds the first draft. Nobody funds the one that works.",
    rawThought: "",
    date: "2026-07-20T10:00:00.000Z",
  },
  {
    id: "f-d-10",
    volumeId: "d-10",
    passage: "Constraint as Method.",
    thought:
      "The brief is the material. Wider is not freer.",
    rawThought: "",
    date: "2026-07-18T10:00:00.000Z",
  },
  {
    id: "f-d-11",
    volumeId: "d-11",
    passage: "Typography Is Argument.",
    thought:
      "Type sets the terms of the reading before a word lands.",
    rawThought: "",
    date: "2026-07-16T10:00:00.000Z",
  },
  {
    id: "f-d-12",
    volumeId: "d-12",
    passage: "Learning by Copying.",
    thought:
      "Copy until you can say what you changed and why.",
    rawThought: "",
    date: "2026-07-14T10:00:00.000Z",
  },
  {
    id: "f-d-13",
    volumeId: "d-13",
    passage: "The Portfolio Is the Wrong Artefact.",
    thought:
      "It shows outcomes and hides the decisions. Fix that.",
    rawThought: "",
    date: "2026-07-12T10:00:00.000Z",
  },
  {
    id: "f-d-14",
    volumeId: "d-14",
    passage: "Notes on Sketching.",
    thought:
      "Rough on purpose so it stays negotiable.",
    rawThought: "",
    date: "2026-07-10T10:00:00.000Z",
  },
  {
    id: "f-d-15",
    volumeId: "d-15",
    passage: "Why Critique Fails.",
    thought:
      "Because nobody states the criteria first.",
    rawThought: "",
    date: "2026-07-08T10:00:00.000Z",
  },
  {
    id: "f-d-16",
    volumeId: "d-16",
    passage: "Craft Under Deadline.",
    thought:
      "Quality is what survives when time runs out.",
    rawThought: "",
    date: "2026-07-06T10:00:00.000Z",
  },
  {
    id: "f-d-17",
    volumeId: "d-17",
    passage: "The Replication Gap.",
    thought:
      "If it does not replicate it was never a finding.",
    rawThought: "",
    date: "2026-07-04T10:00:00.000Z",
  },
  {
    id: "f-d-18",
    volumeId: "d-18",
    passage: "Methods Are the Result.",
    thought:
      "How you looked determines what you found.",
    rawThought: "",
    date: "2026-07-02T10:00:00.000Z",
  },
  {
    id: "f-d-19",
    volumeId: "d-19",
    passage: "On Reading Papers Badly.",
    thought:
      "Abstract, figures, limitations. In that order, then decide.",
    rawThought: "",
    date: "2026-06-30T10:00:00.000Z",
  },
  {
    id: "f-d-20",
    volumeId: "d-20",
    passage: "Citation Is Not Evidence.",
    thought:
      "A chain of citations pointing at nothing.",
    rawThought: "",
    date: "2026-06-28T10:00:00.000Z",
  },
  {
    id: "f-d-21",
    volumeId: "d-21",
    passage: "Sample Size and Story Size.",
    thought:
      "The narrative always outruns the n.",
    rawThought: "",
    date: "2026-06-26T10:00:00.000Z",
  },
  {
    id: "f-d-22",
    volumeId: "d-22",
    passage: "Field Notes as a Form.",
    thought:
      "Write it while it is still uncomfortable.",
    rawThought: "",
    date: "2026-06-24T10:00:00.000Z",
  },
  {
    id: "f-d-23",
    volumeId: "d-23",
    passage: "The Literature Nobody Reads.",
    thought:
      "Written to be counted, not read.",
    rawThought: "",
    date: "2026-06-22T10:00:00.000Z",
  },
  {
    id: "f-d-24",
    volumeId: "d-24",
    passage: "Qualitative Is Not Soft.",
    thought:
      "Rigour is about method, not about numbers.",
    rawThought: "",
    date: "2026-06-20T10:00:00.000Z",
  },
  {
    id: "f-d-25",
    volumeId: "d-25",
    passage: "Prompting Is Interface Design.",
    thought:
      "The prompt box is a text field with no affordances. That is the problem.",
    rawThought: "",
    date: "2026-06-18T10:00:00.000Z",
  },
  {
    id: "f-d-26",
    volumeId: "d-26",
    passage: "Evaluating Generated Work.",
    thought:
      "Judge the consequence, not the intent that is not there.",
    rawThought: "",
    date: "2026-06-16T10:00:00.000Z",
  },
  {
    id: "f-d-27",
    volumeId: "d-27",
    passage: "The Copilot Metaphor Is Wrong.",
    thought:
      "A copilot can fly. This cannot.",
    rawThought: "",
    date: "2026-06-14T10:00:00.000Z",
  },
  {
    id: "f-d-28",
    volumeId: "d-28",
    passage: "Latency Changes the Interaction.",
    thought:
      "Three seconds turns a tool into a request.",
    rawThought: "",
    date: "2026-06-12T10:00:00.000Z",
  },
  {
    id: "f-d-29",
    volumeId: "d-29",
    passage: "Design Systems for Uncertain Output.",
    thought:
      "Design the wrong case first, then the right one is free.",
    rawThought: "",
    date: "2026-06-10T10:00:00.000Z",
  },
  {
    id: "f-d-30",
    volumeId: "d-30",
    passage: "Who Reviews the Model's Work.",
    thought:
      "Approval theatre if nobody can actually check it.",
    rawThought: "",
    date: "2026-06-08T10:00:00.000Z",
  },
  {
    id: "f-d-31",
    volumeId: "d-31",
    passage: "Explaining Without Anthropomorphising.",
    thought:
      "Say what it does, not what it thinks.",
    rawThought: "",
    date: "2026-06-06T10:00:00.000Z",
  },
  {
    id: "f-d-32",
    volumeId: "d-32",
    passage: "Interfaces That Admit Doubt.",
    thought:
      "Confidence is a design decision, usually the wrong one.",
    rawThought: "",
    date: "2026-06-04T10:00:00.000Z",
  },
  {
    id: "f-d-33",
    volumeId: "d-33",
    passage: "The Undo Problem.",
    thought:
      "Reversibility beats permission every time.",
    rawThought: "",
    date: "2026-06-02T10:00:00.000Z",
  },
  {
    id: "f-d-34",
    volumeId: "d-34",
    passage: "Working in Public.",
    thought:
      "The audience changes the work. Decide if that is good.",
    rawThought: "",
    date: "2026-05-31T10:00:00.000Z",
  },
  {
    id: "f-d-35",
    volumeId: "d-35",
    passage: "Standups Are a Symptom.",
    thought:
      "If the work were visible you would not need the meeting.",
    rawThought: "",
    date: "2026-05-29T10:00:00.000Z",
  },
  {
    id: "f-d-36",
    volumeId: "d-36",
    passage: "Estimating Is Guessing With Ceremony.",
    thought:
      "The number is fiction. The conversation is not.",
    rawThought: "",
    date: "2026-05-27T10:00:00.000Z",
  },
  {
    id: "f-d-37",
    volumeId: "d-37",
    passage: "The Cost of Context Switching.",
    thought:
      "Not the minutes lost. The depth never reached.",
    rawThought: "",
    date: "2026-05-25T10:00:00.000Z",
  },
  {
    id: "f-d-38",
    volumeId: "d-38",
    passage: "Documentation as a Product.",
    thought:
      "Nobody owns it, so it rots.",
    rawThought: "",
    date: "2026-05-23T10:00:00.000Z",
  },
  {
    id: "f-d-39",
    volumeId: "d-39",
    passage: "Small Teams, Long Horizons.",
    thought:
      "Continuity beats headcount.",
    rawThought: "",
    date: "2026-05-21T10:00:00.000Z",
  },
  {
    id: "f-d-40",
    volumeId: "d-40",
    passage: "Rituals That Outlive Their Reason.",
    thought:
      "Ask what it was for. Usually nobody remembers.",
    rawThought: "",
    date: "2026-05-19T10:00:00.000Z",
  },
  {
    id: "f-d-41",
    volumeId: "d-41",
    passage: "Deciding Without Consensus.",
    thought:
      "Disagree and commit only works if someone decides.",
    rawThought: "",
    date: "2026-05-17T10:00:00.000Z",
  },
];

/**
 * Pre-computed so the shelf screen never blocks on a Claude call. Regenerated
 * in the background once the volume count changes.
 */
export const seedInterestSummary = {
  text: "You keep circling one idea from several directions: that the measure quietly becomes the brief. It shows up as metrics writing product decisions, as polish freezing structure before it is settled, and as critique losing its footing when there is no author left to question. What you keep reaching for is the second pass \u2014 the articulation and revision nobody makes time for.",
  generatedAt: "2026-08-27T10:40:00.000Z",
  volumeCount: 10,
};
